### ISSUE TITLE
iPad Station Selection Issues

### ISSUE THREAD

**Issue by Furness804** [jpwright/subway#27]
After a while of using the software, I encounter an issue when I go to select a pre-existing station, it will create a new one.

NOTE - I have only used this website on Google on an Apple iPad, and have most of the time encountered this issue.

UPDATE - I used the website in the same search engine on PC and didn’t encounter this issue.

**Comment by Furness804** [comment]
Okay, this is weird, but now I can’t select stations at all. This problem might go away, but if it doesn’t, I might report it as a seperate issue.

**Comment by Furness804** [comment]
Okay, the second issue has gone away.

**Comment by bootmii** [comment]
Reopen? Having the same issue in Firefox on Linux. It doesn't happen right away, but once it does you can't get it to go away unless you save and reload, which lowers ridership (#30).
