### ISSUE TITLE
SECURITY ALERT: Backdoor when clicking "About this game"

### ISSUE THREAD

**Issue by kirbix12** [jpwright/subway#28]
https://github.com/jpwright/subway/assets/80133246/cd00de23-3f61-4bf9-92fd-b2cae2710085

Pretty self-explanatory, but what it supposed to lead to your website is no more for that button, which now instead leads to malicious backdoor websites.

This security issue was first pointed out by a user of a NYCS-based Discord server.

**Comment by jpwright** [comment]
fixed, thank you
